<?xml version="1.0" encoding="UTF-8"?><TSX>
  <project xmlVersion="28">
    <images>
      <image id="0" type="png" value="images/printSetup.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAC8klEQVR42oWS20+ScRjH37vmf1A3
3ag3zqtuuzDbaDOd3mhZayoemqE53KIDC5ZpLfLQUhmm66hiim7Whl0wlREICopgyiseyDOYB+L8
IvDtx1tzuul6ts9+27vn+3mf57cfRR0pjkhTlFVvUOU0GGIE5DQagjkN48EsiS52UaBtpf5XGc+1
4R1PEHu+EHa9f9nxhGDb9ED0dRWlr+2BjLtDZ04VZEnGAr/9DCbXIoQDGH4y0CyGEDqIYnIzgrqh
VVx+NCI/VZApGQvGBWYiMK9HMLEShnaJgcPlQ3wy174fHLHm4MRwU1NTQqZEx7h9DGbI32a2ov+m
CEM154fyhxdustqVp9+ZvLy8hGPhmpqaEoKXXBb2icC2FcMsEViJyLRywK4xbA/AuaSDRV4Im+IB
pj/khozNF/jxMKe9vR0mkwnZ9XrsEgHtjMFGmNmIwkJW0ZMppqfk2NY9w95UL0KrRuxbB2Bsu7Ef
F1hJwel0QiQSnUhXayHc8xIE1/qxPMiHz9wN/+wXWD9VxOICJhKJII7RaITH4znGzkIX3HQtmF05
/Atl8M7eB915C3bFPYgFvBglFovBMAyLQqGAw+FgRXHs6gp4HDIwOx/hXywkE1Thl5aHlf5yeJ0L
4HK5oIRCIWw2G4tMJgNN0xgdHcXou2vwbgwh7JbDN5+H4Ho1XMOlmGlKh21uju1PS0sDJRAIoFKp
WBobG2GeUGOkkw+7huzsaoPPfh2+xTtwqopBd5ejtrb2sD8lJQUUn8+HUqlkkUqleF+XjS1zL0zd
lbD0p2NNXwi6Nxdt1ZeQwUlHVVXVYX9ycjIoHo8X7enpYT+QC0XfCw68hna43l6FlncWipJz+NZ8
G8NqHT73DSA1NZXt7ejoQGJiIqji4uI3BQUF1vz8fHClelTmnIe6pQD0oBha2U2M99ZhZduHZacH
gVAY3FY9kpKS4mELOYXHXiRXaogWCRtQ+eQVHr9swcOWHpTKJgjjLGVtE0RgiB7N/AE9w5BKWFEG
2QAAAABJRU5ErkJggg==]]></image>
      <image id="1" type="png" value="images/printPreview.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABt0lEQVR42o2TSUvDQBiGq39DBe+e
ROl/8CIePHjxF3gXPIoX0ZPaIhUpgorryaW4UKSikbbWrVBcaq1VE7q3SaaZ2tjXmWhEq8UMPGQg
8z0z78eMzfYxmhkdDPs/tDIabX+MDkppoVKpvOm6jr9g/+FwOCbqSey8WFVVEEK+KBaLyOfzSCaT
hkSSJDidzl+SBi7gCzRNQ7lcNr4cRVFQKBSQSqUMQalUAt/E5XKZkp8CXmzCBbxAlmWk0+lfkT57
0vBDwGJ8LeBzntuMkslkjJOIolhfUMt3CT8J70c2m7Uu0PUKfOEE1oVbzB08YunoBZ7QE17LxJrg
8OoRW6Ek7iSChwyF/17GzkUa3vOENcGqICLyrCAQL0GIERwzwiLF8mH8fwHP7/bGEU1RCPcqjqIq
vNcKQgmKBd+zNcEyyxx5IfDdfhRzTp8oZjw31iL4whL8URlnrOgkriHIdt+8VOCa38Bof/twraBa
K8gpFMG7HNZYL1aORczuP2B63oPwziyEqX6yONDWZ97GTnb7CCuq+5hMYoHt6ql7oBrbnYRnpIuY
ghYusfCcDQa7m4b2x3u1vbEevAMXxIXDSvbQMwAAAABJRU5ErkJggg==]]></image>
      <image id="2" type="png" value="images/print.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACaElEQVR42o2S30taYRzGz93o78hu
xP9gF4KhrCUTBKNuZKcfN8LEC71QUGhuAymDQeKWl8EatTEYGIg0h57UyojSTYk2V9tKt1x2/Hn8
9ew975YrsG0vfDjwfp/neb/f9z0Mc2kp7eG76pl4UDMb7xCgccdrmtmNmtq13rlp4eaZf62hR1zj
lK/hR7mOQukXp3wd6WMe9tdHmHy8Xx26t3rj2gC1K1o9rwjY/twiNBH/JCB8UEe92cb2cQsPVo+g
sL55dm3AsCtaEwN2SMDOlxY2DxvgPgjI5ssQO8ufVaB0hJs9zXNzc33DrnWhWBaQJKclT9q/u2gg
+L4Cf6qEIhlNdT8i6HS6vivm6enpCUKJXBbOSED6pIN3JGCPBCUOm3SMtf0qqTVwy8lhbGyspNVq
Jy7MyoWFBSQSCdyZiaFAAjK5DtKE5Nc2dskoMdJFhIxSIAG3H8YQiURgNpuhUqmUYsAeWcjlcrDb
7f+FqOU4DiMjIwdigNBqtSCytbUFnuf/SjQaxYXeZDJ1GIfDAUEQKCsrK8hmszSoF2JtcXGxq2dZ
FozNZkM6naZ4vV5kMhmEQqGeiBryWl29XC4HY7FYEAwGKW63G6lUCoFAoCfJZBJOp7Orl0qlYMgc
8Pv9FI/HA3InFKvVCqPRSNskT4bBwUEoFAq6d6EfGBgAYzAY2ktLS3RDNC6/eIW1t+s9eb78EjKZ
jGp9Ph/6+/vBjI+PP9Xr9Xujo6NgPTFUawJOzwV8J+SLdRwXajj8VsbHHI9qvQF2PgaJRCKad8nX
duWPZD3x9tSTTUx5/zBJ2aCINXY+3r7s+Ql86JM95BH+oQAAAABJRU5ErkJggg==]]></image>
      <image id="3" type="png" value="images/select.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAeElEQVR42mNgQANTjn3/z0AJABnQ
s5cCQ0AGnLtGgSEgjSADQLh47fP/FBkAwlFzrpFmCMhWZANINgSbASQZgssAEA7qOfefbC/AMEFD
QIqQNZIcBsiakA1zqj72n2gDkG0EOZlkA5D5MANIMgQdgDRSbADZmgkBAJUX6jjE5pZGAAAAAElF
TkSuQmCC]]></image>
      <image id="4" type="png" value="images/pan.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAApklEQVR42p2SMQ6AIAxFOZujo6NX
YXXkCK6OjI5egdGR1dEjVAspKUSb6k9+bMA+flFjBLkNAG20mgMAmup4ZFt/gl2zxWZqIFAB3I1U
j3OE17gqwJIB9KyEUTmEj8AToFPt9hrCT5ISlJoAuEiR+MtPptPLffCFdNteBnB3U6gB7bxiEj5/
C1EB2s+JxC+AwYX/gN6G559JO8orAIWbv5s1EBXgiy70e1lUpvzebAAAAABJRU5ErkJggg==]]></image>
      <image id="5" type="png" value="images/marqueeZoom.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA00lEQVR42q2SIRKDMBBFuUqPge0R
egWOgIytjETGIiMjsciVyFhkZOU2f6fb0ilQoM3Mzu6Q/Lc/WYrin6uLzNPwlCQ2iyneOCZ+i5AB
rht5k9g4mo2vkDAk6SaHcw0YAjW+obY+rgDoBZiK1RWNzI3vlwGePh0gqwPd2wSYip8OkNthGeDy
K+IaS4+I/aZx65OwIcrMdZT6FiLO9x/8lYMp1yE4CKvS+ZHRuXcVJ/JMbc2+Lnn3HxrMWSAxWMmu
Ou2HoHNnL79BIFInhwAKOSyeW3ejYV19bWpvrAAAAABJRU5ErkJggg==]]></image>
      <image id="6" type="png" value="images/interactivezoom.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA1UlEQVR42q2SrxKDMAzG9yp7DCyP
sFfgEZC1k5XIWmRkJBYZiaxFVk5mTXbZsQ0YsPUuV/rn++VLyun0z9FF5mkAJY3NYoo3jolfAjMg
dCPvEpeu17C9rxAc0od4CpHwEFcA9ADYZReIXTs81zQyN9AvA2ACEDcGkG9zJ3ubAO8lCEBdZeAi
IOQu4gzEsst504T1l/AY9c2t81a/inP9A1wZXbEOkYti1Xogs2TuQ8WJgKmtGeqCd/+h6EqFRPQ6
h+q8HyKZO3/5DSIic3IIYJDD4rlxB97uXXAfX7uwAAAAAElFTkSuQmCC]]></image>
      <image id="7" type="png" value="images/zoomIn.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA0ElEQVR42q2SIRKDMBBFe5UeA9sj
9AocARlbGYmMRa5ciUWuRMYiIyu32Z3uNHQKFNrM/Ekm4b/92XA6/XP0kbkUUFJ9baZ455h4JsyA
0E+8y+wCqWxvE4JjelXMawPIWiAiD3EFQGlW+V00MbcwLANgA2BnmwCLW/bAruG6cRkQchexgJQ9
kD05b9uw/hIeo765dd7SqDnff4Qbo6vWIfKhRNUEz1kqD6HmRMDUNQxNxbv/UHQXhUT0Oof6vB8i
lXt//Q0iJktyCGCQw+ZP4wHw0l8XtgzUIwAAAABJRU5ErkJggg==]]></image>
      <image id="8" type="png" value="images/zoomOut.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAyklEQVR42q2SKw7DMAyGe5Udo3RH
2BV6hMLQwcDC0EJDw9BCw8LQwsBBL85mLZP63iL9spXk/+w8quqfwwfmUkAxa7eZwoND5C9hAjg/
8SGz5KpdEBzjp2LK1VzmFsIKgF4A42hWNDF3MCwDYAOga5uAsnVtX6Ppx2WAS7eIBaQ0y5ysd51b
fwmLIb+53rx2k83p/CPcGU29DpGN0mo++ztK5cE1HAmY+pahrfnwD0VzzZCANkfXXI5DpLK3t98g
YtJOTgEUcto8N541NGSMkK8K/AAAAABJRU5ErkJggg==]]></image>
      <image id="9" type="png" value="images/fitInView.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA2ElEQVR42q2SKxLDIBCGc5UeIzZH
6BVyhEhsJTISG4lExkYikdhIZOWWfzuboTPNs2VmZ5eB/9sHVNU/1xiJSrM+sR0W+/ikmOjDXAaY
caZD4kZNbIjL/S7EhcTZ+HKOBYBYgNrGDYB/A0Qo4mU/E/V2WgfYAiBCeDGcKeP3AVKuCGUO8GoI
6wCTp4g2lqEVYhjO+95sv4R2kd9cnlL6Z3HuP9gHOVVvQ3ARpaJf8cg8mZaSt+SHjmxX0+kf6lTD
kOg0e9PezkOQedT33yAQSSWXAAK5LP62XmTiXoOxHE73AAAAAElFTkSuQmCC]]></image>
      <image id="10" type="png" value="images/overview.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABt0lEQVR42mNgIBPo9Wu3qDcrH8ap
oHvdw//NKy79xCXvOsXhtcN0m/+YMrEM3DNm9i4uX3x+XVDnET+QkH63VrrXCvvd/xuusgW2H20p
W3j+6bRZvfcYAhnEwHpClvj+T1oS/WLt6rVLGo5U/HedZfcF2czQNd5HEraG/58+fcIvoKv+g1yH
Ymnu+vSH2ZsTe/Zs3KMXvzDyf9LqyD8oCvoZJGcvn/0NxGyYdTipa8Lc67hDB80L/0P/M4du8DoU
Mtvv354N+0OyN8WfBlr4G6teSeun/xWdn/3X9Hr+3yDo+X/LqBf/HZJe/vfIfPU/c3vC/zVr1twH
evUvyMs4DYCxO/vmzqqdedgcxPYvePWfoZOBl2DcKjo9QwlMtzn2x0HhElb+GjPgsAEtn+f/kQMz
dW30e5Bh8fVv/mfOW38DFDagMMJpgGHw8/8wZ89ZMec8zNlp7W//w6I7dmH4f2QXohgACjS7+Jf/
3dJf/vfNe/U/tOz1/5jaN//z+yEGZKxJ+hm+1P8/sgtxRp3nCrtqnV4NK5A0SAwkh9MLoDQNTNs7
cHkNlCfwBqJ6k3KzXq+2H8NAAADGqgg+rcdQGwAAAABJRU5ErkJggg==]]></image>
      <image id="11" type="png" value="images/circulardeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAw0lEQVR42mNgwAGmHPv+v2Xr+//F
a5//ZyAV9PT0gDUfO/f+f9SUa/9BfJI0g2iQRhB2qj72H1kcr3Ozl+J3rmaP5n/FasX/IBpFAt25
uLDTHMv/QWu9wIagGACyGdm52LwFwoZAm0GGYBiAy48wjYTUYUhg04jXgOy9Uf9hGF9o4wxEkMat
99b+7zlWjTcWcAciyOZzLUAXJOM1AG8govsxaKvXf6+lTmANBBMSNkNATp1yDhL3JGlG9i/IaxgB
NugAAHtqyW6XUk8wAAAAAElFTkSuQmCC]]></image>
      <image id="12" type="png" value="images/hierarchicaldeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuElEQVR42qWSIQ/DIBCF+1cqKydr
kUgkdrJyElt5ElmLRCJnkZWTs5WVk29A0qRNSGjpSy4h5O7LuwdNk5H2P4xuxcsuaGoUh/28QupP
HWAwSxpmyl8HEBFy58vDm4TjEJaDmx51gDCsZwKbbgCkFXhQh9sZnM5keEtstb/vgotYrWpRBLiv
Bc3joTHmEFfqSutEAHkVHDwPjTGHPkCKDm5nsJd0Itk+9Yw5XfoHOXHD0j/oawEl/QHST4gGXc7O
gwAAAABJRU5ErkJggg==]]></image>
      <image id="13" type="png" value="images/orthogonaldeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA8klEQVR42r1SoRKDMAzdryCRSCwS
icQikUjsZGXlLLISia1ETs5OTk5mvBwpYbDtbrtb7t5Bk5fX9qUH6+8EHPsbo3FXOswheZ3bBAh+
XFDaMxljGFLTOQ0WqLsrEwRZ68NuezmJIKAXq+Qe8a8C9VBS4XJG3qWU2DjUYhNT1EaE70uB3GVk
RxOAtZiXnVIqXcEiGwEBdpZmMx65SYujvjmBDjRIc+sbSibyxxPoSCcSiOmMxCwe4B+5twJfTeEr
gcZXhJEBzyTcE2ZpA/UY+Qpo7C+OzXp+6zIJCOj8agoQQHM9VJsTgIh6MEuZmGkTf4kHC99SaPEo
FQ0AAAAASUVORK5CYII=]]></image>
      <image id="14" type="png" value="images/symmetricdeep.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAvUlEQVR42r1QLQ+DMBDlryCRyNpK
ZGUtshKJRVYiZysrK7GVlZOzSOTkrXfJCGPL2lXsJefufVZVARrdAF491lDCr/iFgbAdiRQJtJHI
okhRAq31d9Ls7zC5DQa77o/SCYrcGZZ2RLIPG8j5CuiGh+Q5aIqdFFBmJTIf/f7cGQ5qkdDmjvap
Z7L7E8PSkxveeQOeVSES3c2C9uPbBtkCSFYxyXEDaUV6g+yeL519T27Hzj9h7xymcoFz57/iAdEQ
msrhh+E9AAAAAElFTkSuQmCC]]></image>
      <image id="15" type="png" value="images/globalLayout.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuElEQVR42mNggIK9Tgz/GYgEGGpB
AqQaAFcP45BjAFY9U459/9+y9f3/4rXP4ZJRW4P+B631+u+11JKwJSDNx869/x815dr/np4eMAZp
nnKu57/lHCIMAGkEYafqY3DFXkud/mfvjfpv2KNJnDdBthIjRhsDio8lg50LwjAxTaDTFasV/2sS
4wWQxq331v7vOdcCD0QnYOCBAhJkCFEGgDRn702GKwaFPghjNYAqCYmipEyVzDSgAAC1Z54JsS6C
hwAAAABJRU5ErkJggg==]]></image>
      <image id="16" type="png" value="images/incrementalLayout.png"><![CDATA[iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAyElEQVR42tWSKxODMBCE81eQyEps
JBIZWxmJxFaejKxFRkbGRiIra5HIyi1HJ0zLo+1ATW/mTOb2u80mQmwoLwXE3toNYcAixIQbTq5D
aVtscsHi0HRQ5gIiGlq5AoXNkdcZZoBoJdJ03Q5iWYVxmMWmIWTnByDOjg6m9+Gtz5vyWkJ7hQOl
mM3PaAuA6dmL62kQpT8O27jXAG+TZKG7WlCoxvO0t86dVAk+vicDWKx7J/EVZB8eB7kI+OZXcXgM
WQX87H//Z90BLpKh7vcb0uIAAAAASUVORK5CYII=]]></image>
    </images>
    <module tags="Node, Edge, Customer, Document, Record, TripleID">
      <schema name="GraphViz">
        <attributeTypes/>
        <modelElementTypes>
          <modelElementType name="Node">
            <attributeTypes>
              <attributeType identifier="true" name="ID">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="Property">
                <type name="StringValue"/>
              </attributeType>
            </attributeTypes>
          </modelElementType>
          <modelElementType name="Edge">
            <attributeTypes>
              <attributeType identifier="true" name="ID">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="To">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="From">
                <type name="StringValue"/>
              </attributeType>
            </attributeTypes>
          </modelElementType>
          <modelElementType name="Customer">
            <attributeTypes>
              <attributeType identifier="true" name="ID">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="City">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="DOB">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="FamilyName">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="GivenName">
                <type name="StringValue"/>
              </attributeType>
              <attributeType identifier="false" name="SSN">
                <type name="StringValue"/>
              </attributeType>
            </attributeTypes>
          </modelElementType>
        </modelElementTypes>
      </schema>
      <views>
        <drawingView name="Drawing">
          <mapping>
            <modelRules>
              <rule>
                <actions>
                  <setDrawingLayoutPropertiesAction description="Set Drawing Layout Properties" id="$rootDrawing()">
                    <actionList>
                      <setOptionAction optionName="layout:all:graph:layoutStyle" value="LAYOUT_STYLE_SYMMETRIC"/>
                    </actionList>
                  </setDrawingLayoutPropertiesAction>
                </actions>
              </rule>
            </modelRules>
            <modelElementRules>
              <rule elementTypeName="Node">
                <actions>
                  <addNodeAction description="Add Node" id="node.Node.&lt;ID&gt;" tags="Node"/>
                  <addNodeLabelAction description="Add Node Label" id="nodeLabel.Node.&lt;ID&gt;" parent="node.Node.&lt;ID&gt;" tags="Node" text="node.Node.&lt;Property&gt;"/>
                </actions>
              </rule>
              <rule elementTypeName="Edge">
                <actions>
                  <addEdgeAction description="Add Edge" id="edge.Edge.&lt;ID&gt;" source="node.Node.&lt;From&gt;" tags="Edge" target="node.Node.&lt;To&gt;"/>
                  <addEdgeAction description="Add Edge" id="edge.Edge.&lt;ID&gt;" source="node.Node.&lt;To&gt;" tags="Edge" target="node.Customer.&lt;From&gt;"/>
                  <addEdgeAction description="Add Edge" id="edge.Edge.&lt;ID&gt;" source="node.Customer.&lt;To&gt;" tags="Edge" target="node.Node.&lt;From&gt;"/>
                  <addEdgeAction description="Add Edge" id="edge.Edge.&lt;ID&gt;" source="node.Customer.&lt;To&gt;" tags="Edge" target="node.Customer.&lt;From&gt;"/>
                </actions>
              </rule>
              <rule elementTypeName="Customer">
                <actions>
                  <addNodeAction description="Add Node" id="node.Customer.&lt;ID&gt;" tags="Node"/>
                </actions>
              </rule>
              <rule elementTypeName="Document">
                <actions>
                  <addNodeAction description="Add Node" id="node.Document.&lt;ID&gt;" tags="Node"/>
                </actions>
              </rule>
              <rule elementTypeName="Record">
                <actions>
                  <addNodeAction description="Add Node" id="node.Record.&lt;ID&gt;" tags="Node"/>
                </actions>
              </rule>
              <rule elementTypeName="TripleID">
                <actions>
                  <addNodeAction description="Add Node" id="node.TripleID.&lt;ID&gt;" tags="Node"/>
                </actions>
              </rule>
            </modelElementRules>
          </mapping>
          <behavior>
            <toolbar embedded="true" floatable="false" location="North" minimumHeight="21" minimumWidth="0" name="Default" orientation="Horizontal">
              <actionItem action="General.Print Setup" mnemonic="u" resource="0" tags="GLOBAL_TAG" text="Print Setup">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="General.Print Preview" mnemonic="r" resource="1" tags="GLOBAL_TAG" text="Print Preview">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="General.Print" mnemonic="P" resource="2" tags="GLOBAL_TAG" text="Print">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Tool.Activate Tool" mnemonic="e" resource="3" tags="GLOBAL_TAG" text="Select">
                <disabledIcon/>
                <customization>
                  <tool name="Select Tool"/>
                </customization>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Tool.Activate Tool" mnemonic="a" resource="4" tags="GLOBAL_TAG" text="Pan">
                <disabledIcon/>
                <customization>
                  <tool name="Pan Tool"/>
                </customization>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Tool.Activate Tool" mnemonic="M" resource="5" tags="GLOBAL_TAG" text="Marquee Zoom">
                <disabledIcon/>
                <customization>
                  <tool name="Marquee Zoom Tool"/>
                </customization>
              </actionItem>
              <actionItem action="Tool.Activate Tool" mnemonic="Z" resource="6" tags="GLOBAL_TAG" text="Interactive Zoom">
                <disabledIcon/>
                <customization>
                  <tool name="Interactive Zoom Tool"/>
                </customization>
              </actionItem>
              <actionItem action="General.Zoom In" mnemonic="n" resource="7" tags="GLOBAL_TAG" text="Zoom In">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="General.Zoom Out" mnemonic="t" resource="8" tags="GLOBAL_TAG" text="Zoom Out">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="General.Fit" mnemonic="F" resource="9" tags="GLOBAL_TAG" text="Fit">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="General.Overview" mnemonic="v" resource="10" tags="GLOBAL_TAG" text="Overview">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Layout.Circular Layout" mnemonic="C" resource="11" tags="GLOBAL_TAG" text="Circular Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Hierarchical Layout" mnemonic="H" resource="12" tags="GLOBAL_TAG" text="Hierarchical Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Orthogonal Layout" mnemonic="O" resource="13" tags="GLOBAL_TAG" text="Orthogonal Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Symmetric Layout" mnemonic="S" resource="14" tags="GLOBAL_TAG" text="Symmetric Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <separatorItem tags="GLOBAL_TAG"/>
              <actionItem action="Layout.Global Layout" mnemonic="G" resource="15" tags="GLOBAL_TAG" text="Global Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
              <actionItem action="Layout.Incremental Layout" mnemonic="I" resource="16" tags="GLOBAL_TAG" text="Incremental Layout">
                <disabledIcon/>
                <customization/>
              </actionItem>
            </toolbar>
            <contextMenu/>
            <toolConfiguration>
              <tool name="Select Tool" type="SelectTool">
                <customization>
                  <moveChildTool name="Move Tool"/>
                  <resizeChildTool name="Resize Tool"/>
                  <deleteChildTool name="Delete Tool"/>
                  <editTextChildTool name="Edit Text Tool"/>
                  <reconnectChildTool name="Reconnect Tool"/>
                </customization>
              </tool>
              <tool name="Move Tool" type="MoveTool"/>
              <tool name="Resize Tool" type="ResizeTool"/>
              <tool name="Delete Tool" type="DeleteTool">
                <customization>
                  <toolRules/>
                </customization>
              </tool>
              <tool name="Edit Text Tool" type="EditTextTool"/>
              <tool name="Reconnect Tool" type="ReconnectTool"/>
              <tool name="Pan Tool" type="PanTool"/>
              <tool name="Marquee Zoom Tool" type="MarqueeZoomTool"/>
              <tool name="Interactive Zoom Tool" type="InteractiveZoomTool"/>
              <tool name="Link Navigation Tool" type="LinkNavigationTool"/>
            </toolConfiguration>
          </behavior>
          <preferences>
            <preference name="rendering:blinkInterval" value="0.0"/>
            <preference name="highlightedTags" value="Node, Edge"/>
            <preference name="focusToHighlightedObjects" value="true"/>
            <preference name="highlightColor" value="255 255 1 120"/>
            <preference name="overviewWidth" value="185"/>
            <preference name="overviewHeight" value="165"/>
            <preference name="overviewEmbedded" value="true"/>
            <preference name="showScrollControl" value="true"/>
            <preference name="showZoomControl" value="true"/>
            <preference name="initiallySelectedTool" value="Select Tool"/>
            <preference name="viewingTool:interactiveZoomReversedDirection" value="false"/>
            <preference name="animation:viewportChangeAnimation" value="true"/>
            <preference name="animation:viewportChangeAnimationDuration" value="Low"/>
            <preference name="autoLayout" value="false"/>
            <preference name="initialLayout" value="true"/>
            <preference name="interactive:showLayoutProgress" value="true"/>
            <preference name="interactive:layoutPreserveFocus" value="false"/>
            <preference name="interactive:layoutDrawingFitting" value="Fit To Canvas"/>
            <preference name="animation:layoutInterpolationAnimation" value="true"/>
            <preference name="animation:layoutFadeAnimation" value="false"/>
            <preference name="animation:layoutAnimationDuration" value="Low"/>
            <preference name="editingCommand:compressMetaEdges" value="true"/>
            <preference name="editingCommand:applyGeometricAdjustment" value="true"/>
          </preferences>
        </drawingView>
      </views>
    </module>
  </project>
</TSX>
